### ISSUE TITLE
AM/PM style and Translation are corrupted!

### ISSUE THREAD

**Issue by theramez** [slametps/MMM-PrayerTime#10]
greetings slametps,
thanks for this great module,
here is the problems
1- in `TODAY` column the 12H AM/PM style is really bad "it shows time in line and 'AM' in other line! although it's normal in `TOMORROW` column.
2- can't display the module with `'id'` language or any other language! (I've made an arabic json translation `ar.json` then add the proper code to `getTranslations: function()` then changed `config.js` to `language: "ar",` but still in english, even changing lang. to id doesn't matter still appears in english only?
lastly, how can I upload my translation to your repository? if you're interested :+1:

**Comment by theramez** [comment]
EDIT: Fixed the AM/PM style issue by editing `MMM-PrayerTime.css` and enlarging table pixel size, for reference here is what it should
``` .MMM-PrayerTime table {
  width: 280px;
}

.MMM-PrayerTime td {
  width: 190px;
}

.MMM-PrayerTime .occasion-name {
  text-align: center;
}
.MMM-PrayerTime .occasion-time {
  text-align: center;
}
```
I've a 22" display so if you've a bigger monitor you should higher the `px` values more..

Translations still has a serious problem, It never recognize any language except english and I managed to trick that by changing my language file name to `en.json` and discovered that even english has a minor error in translation it didn't translate `TODAY` it should be `Today` [here](https://github.com/slametps/MMM-PrayerTime/blob/c08537ed17f063f9dd7ebc41cc8adb26d6848198/MMM-PrayerTime.js#L48) same goes for `TOMORROW` nothing called that in fetched data it should be `Tomorrow` [here](https://github.com/slametps/MMM-PrayerTime/blob/c08537ed17f063f9dd7ebc41cc8adb26d6848198/MMM-PrayerTime.js#L52)

**Comment by slametps** [comment]
> greetings slametps,
> thanks for this great module,
> here is the problems
> 1- in `TODAY` column the 12H AM/PM style is really bad "it shows time in line and 'AM' in other line! although it's normal in `TOMORROW` column.
> 2- can't display the module with `'id'` language or any other language! (I've made an arabic json translation `ar.json` then add the proper code to `getTranslations: function()` then changed `config.js` to `language: "ar",` but still in english, even changing lang. to id doesn't matter still appears in english only?
> lastly, how can I upload my translation to your repository? if you're interested 👍

you can do a PR (pull request) for any changes/modification you made.
