### ISSUE TITLE
Script corrumpting my config.js

### ISSUE THREAD

**Issue by OththeGentel** [slametps/MMM-PrayerTime#13]
Salamo aalaykoum brothers,
I'm having some hard time configuring this module into my MM.
here is mine, please help me guys find where is the bottleneck and shukran jazilan.
{
			module: "MMM-PrayerTime",
			header: "أوقات الصلاة",
			position: "lower_right",
			config: {
			apiVersion: '1.0',
      		        lon: -73.587807,
     	        	lat: 45.508839,
			timezone: Canada/Montreal,
			timeFormat: 24,
			method: 2,
			playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
			notDisplayed: ['midnight', 'sunset'],
			useUpdateInterval: true,
			updateInterval: 86400 * 1000,
			animationSpeed: 2.5 * 1000,
			language: en,
			showAdzanAlert: true,
			alertTimer: 15000
			}
		},

**Comment by slametps** [comment]
timezone: 'Canada/Montreal',

**Comment by OththeGentel** [comment]
Thank you, I'll try it :)
