### ISSUE TITLE
Prayer Times from Turkish Diyanet (official turkish time)

### ISSUE THREAD

**Issue by erkilic** [slametps/MMM-PrayerTime#16]
Hello,
is it somehow possible to show the prayer times generated by the official turkish "Diyanet" organization?
Thx in advance.

Gürkan

**Comment by slametps** [comment]
I get the data from web service API provided by http://api.aladhan.com. Of course, it is possible if official turkish "Diyanet" organization provided open API.

**Comment by erkilic** [comment]
thx slamet,

 

but unfortunately I could’t find an open API from Diyanet ☹

 

another question:

I cannot hear adzan sounds coming out from my audio connector and loudspeaker connected to the pi.

if I go into the „res“ directory per file-explorer and click on one of the mp3 files, my vlc media player starts and the adzan is played correctly via 

the audio connector and the connected loudspeaker.

any idea what is wrong in my setting of MMM-PrayerTime ?

 

kind regards

gürkan

 

 

 

Von: Slamet PS <notifications@github.com> 
Gesendet: Mittwoch, 23. Januar 2019 07:57
An: slametps/MMM-PrayerTime <MMM-PrayerTime@noreply.github.com>
Cc: erkilic <mail@erkilic.de>; Author <author@noreply.github.com>
Betreff: Re: [slametps/MMM-PrayerTime] Prayer Times from Turkish Diyanet (official turkish time) (#16)

 

I get the data from web service API provided by http://api.aladhan.com. Of course, it is possible if official turkish "Diyanet" organization provided open API.

**Comment by erkilic** [comment]
sorry but one more question…

Can I increase somehow the font-size or change the color of it? 

I’m a newby and have less knowledge about html/css/js programming (have programmed in c and a little bit in python).

 

kind regards

gürkan

 

 

 

Von: Slamet PS <notifications@github.com> 
Gesendet: Mittwoch, 23. Januar 2019 07:57
An: slametps/MMM-PrayerTime <MMM-PrayerTime@noreply.github.com>
Cc: erkilic <mail@erkilic.de>; Author <author@noreply.github.com>
Betreff: Re: [slametps/MMM-PrayerTime] Prayer Times from Turkish Diyanet (official turkish time) (#16)

 

I get the data from web service API provided by http://api.aladhan.com. Of course, it is possible if official turkish "Diyanet" organization provided open API.

**Comment by slametps** [comment]
you can modify the font-size or text-color, by modifying MMM-PrayerTime.css epecially for *.occasion-name* and *.occasion-time*. You can refer to CSS documentation.

**Comment by milkywade** [comment]
https://github.com/slametps/MMM-PrayerTime/issues/17#issuecomment-462926240

**Comment by erkilic** [comment]
thx slametps! 

⁣BlueMail for Android herunterladen ​

**Comment by erkilic** [comment]
thx slamet. I’m lerning more and more, using CSS.

 

 

Von: Slamet PS <notifications@github.com> 
Gesendet: Dienstag, 12. Februar 2019 18:27
An: slametps/MMM-PrayerTime <MMM-PrayerTime@noreply.github.com>
Cc: Gürkan Erkilic <mail@erkilic.de>; Author <author@noreply.github.com>
Betreff: Re: [slametps/MMM-PrayerTime] Prayer Times from Turkish Diyanet (official turkish time) (#16)

 

you can modify the font-size or text-color, by modifying MMM-PrayerTime.css epecially for .occasion-name and .occasion-time. You can refer to CSS documentation.
