### ISSUE TITLE
Adzan doesn't work

### ISSUE THREAD

**Issue by erkilic** [slametps/MMM-PrayerTime#18]
I cannot hear adzan sounds coming out from my audio-jack and loudspeaker connected to the pi.
if I go into the „res“ directory per file-explorer and click on one of the mp3 files, my vlc media player starts and the adzan is played correctly via the audio-jack (pi audio connector) and the connected loudspeaker.
any idea what is wrong in my setting of MMM-PrayerTime ?
thx in advance

**Comment by slametps** [comment]
you should modify command to play adzan in file node_helper.js. Currently it will output the audio to HDMI via omxplayer.

```javascript
var adzanCmd = '/usr/bin/omxplayer -o hdmi modules/MMM-PrayerTime/res/' + adzanSound + ' &';
```
replace **hdmi** with **local** or **both**.
