### ISSUE TITLE
Adzan sound not playing

### ISSUE THREAD

**Issue by alabdou6** [slametps/MMM-PrayerTime#19]
Dear Brother,

GOD bless you for that great program you have designed.

I'm having a problem with:
1- Notification not showing?
2- Adzan not being played?

As I can understand from the node.helper, the sound will only play when notification being displayed?

FYI, I have played the new adzan sound through my HDMI using the command 
" /usr/bin/omxplayer -o both /home/pi/MagicMirror/modules/MMM-PrayerTime/res/adzan-ahmedhadad.mp3 "

Would you please help solving this issue? is the notification mandatory to allow sound to be played?

[node_helper.zip](https://github.com/slametps/MMM-PrayerTime/files/2979297/node_helper.zip)

Regards

**Comment by slametps** [comment]
Can you post your config.js for the module?
Can you play and hear the adzan successfully from shell?

**Comment by alabdou6** [comment]
Hi,
Below is the part from config.js

		{
			module: 'MMM-PrayerTime',
			position: 'top_left',	// This can be any of the regions. Best result is in the top_left/top_right.
			config: {
			apiVersion: '1.0', // please, leave unchanged. reserved for future use.
			lat: 30.04444, // latitude of your position (city)
			lon: 31.2357, // longitude of your position (city)
			timezone: 'Africa/Cairo', // please refer to http://php.net/manual/en/timezones.php
			timeFormat: 24,
			method: 5,
			playAdzan: ['Fajr','SunRise', 'Dhuhr', 'Asr','Maghrib', 'Isha'],
			notDisplayed: ['midnight','Imsak' ,'sunset'],
			useUpdateInterval: true,
			updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
			animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
			language: 'en',
			showAdzanAlert: true,
			alertTimer: 15000
				}
		},

And, yes, I can play sound via shell.

Thanks for your intense reply.

**Comment by alabdou6** [comment]
Dear brother,

I found that even using your alarm module I can't hear the sound through HDMI, I had to plug an audio jack speaker!!
I think it will be the same issue with the prayer time module even with the omx player command "both" and not only "hdmi".

I will test it with Fajr and Dhuhr pray and provide update.

Gazak ALLAH khaiyran.

**Comment by alabdou6** [comment]
Hello Brother,

Sorry for opening this issue again. But yet, even after plugging an external speakers to get the sound through the audio jack!
The adzan sound doesn't play unless I do it through shell for testing!

Would you please help, I see this issue as a mandatory as I'm planning to learn my kids praying as they reached 8 and there are no masjeds around my area to encourage them to pray once they hear the adzan, and I will depend on this magic mirror for that.

Regards

**Comment by slametps** [comment]
is it working with "-o both" option?

**Comment by alabdou6** [comment]
Sallam Alikom Brother,

Unfortunately, I have checked the node_helper.js and yes it contains the  "-o both" option, but it doesn't yest working.

Looking through the node_helper.js file, I found that an if condition applied to the notification as in the attached image.

![image](https://user-images.githubusercontent.com/48689545/68072968-2ccb0300-fd94-11e9-979c-e80b7e193124.png)

""

socketNotificationReceived: function(notification, payload) {
    console.log(this.name + " node helper received a socket notification: " + notification + " - Payload: " + payload);
    if (notification == "PLAY_ADZAN") {

""

node_helper.js file:

######################

/* Magic Mirror
 * Node Helper: MMM-PrayerTime
 *
 * By Slamet PS/slametps@gmail.com
 * MIT Licensed.
 */

var NodeHelper = require("node_helper");
var async = require('async');
var exec = require('child_process').exec;

module.exports = NodeHelper.create({
	// Subclass start method.
	start: function() {
		console.log("Starting node_helper.js for MMM-PrayerTime.");
	},

	socketNotificationReceived: function(notification, payload) {
    console.log(this.name + " node helper received a socket notification: " + notification + " - Payload: " + payload);
    if (notification == "PLAY_ADZAN") {
      var adzanSound = 'adzan.mp3';
      if (payload.occasion) {
        if (payload.occasion=="FAJR") {
          adzanSound = 'adzan-fajr.mp3';
        }
        else if (payload.occasion=="IMSAK") {
          adzanSound = 'imsak.mp3';
        }
      }
      var adzanCmd = '/usr/bin/omxplayer -o both modules/MMM-PrayerTime/res/' + adzanSound + ' &';
      async.parallel([
        async.apply(exec, adzanCmd)
      ],
      function (err, res) {
      });
		}
	},
});

######################

I think its not working because it doesn't display any notification??!!

Do you think I should grant any permission to any app?
Or we can bypass the notification condition somehow?

Regards

**Comment by alabdou6** [comment]
Hello Brother.

Would you please help ?
Please to find my previous comment. 

Jazak  ALLAH khairan

**Comment by slametps** [comment]
Please change your config to:

`playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],`
