### ISSUE TITLE
Config is not working

### ISSUE THREAD

**Issue by aimanyusof94** [slametps/MMM-PrayerTime#2]
Can you show the working example of config you have written? 
I've been writing the same thing over and over again for the last day. I am a noob and hoping to utilise this module. 

Thanks in advance.

**Comment by slametps** [comment]
What's not working of yours?
Here is my config for the module:

`
		{
			module: 'MMM-PrayerTime',
			header: 'Jadwal Sholat',
			classes: 'default everyone', // don't forget this if you use MMM-FacialRecognition
			position: 'top_left',
			config: {
				lat: -6.196290,
                                lon: 107.175097,
                                timezone: 'Asia/Jakarta',
                                method: 5,
                                useUpdateInterval: false, // set this to false because I want to update schedule using MMM-ModuleScheduler
                                updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
                                animationSpeed: 2.5 * 1000, // Speed of the update animation. (Milliseconds)
			}
`

And an entry of MMM-ModuleScheduler to trigger praying time update:

`
		{
                       module: 'MMM-ModuleScheduler',
                       classes: 'default everyone',
                       config: {
      			  notification_schedule: [
			          {notification: 'PRAYER_TIME', schedule: '1 0 * * *', payload: {type: 'UPDATE_PRAYINGTIME'}}
      			  ]
    	               }
                 },


`

**Comment by aimanyusof94** [comment]
Thank you for quick response. 
I can see that I'm missing a few single quote here and there. And of course, I have no entry in my MMM-ModuleScheduler. 

I tried yours and it is working. Thanks man. You are a good man.
