### ISSUE TITLE
remove Tommorow's time

### ISSUE THREAD

**Issue by TouhaMushir** [slametps/MMM-PrayerTime#20]
Thanks for an awesome Module. 

Is it possible to remove "tomorrow" time column for a cleaner look? Thanks a lot !

**Comment by slametps** [comment]
unfortunately, it is not possible currently. But, I'll try to add new option (config) to display or not the tomorrow column.

**Comment by TouhaMushir** [comment]
Thanks , I will look out for an update on this. Appreciate your help.

**Comment by slametps** [comment]
Now you can update you repo with the latest version (git pull). I added new option: showTomorrow, set to false to hide TOMORROW column.

**Comment by TouhaMushir** [comment]
Thank you!!

**Comment by TouhaMushir** [comment]
Worked . Thank you
