### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by MrGitGo** [slametps/MMM-PrayerTime#21]
I have wrote for lat and lon 51.48165    7.21648 values and for time zone: 'Europe/Berlin' but it is not working. I always get an error. What am I doing wrong?

**Comment by slametps** [comment]
Can you paste your config here?

**Comment by MrGitGo** [comment]
```
{
		module: 'MMM-PrayerTime',
		position: 'top_left',	// This can be any of the regions. Best result is in the top_left/top_right.
		config: {
			apiVersion: '1.0', // please, leave unchanged. reserved for future use.
			lat: 51.5388, // latitude of your position (city)
			lon: 7.22572, // longitude of your position (city)
			timezone: 'Europe/Berlin', // please refer to http://php.net/manual/en/timezones.php
			timeFormat: 24,
			method: 5,
			playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
			notDisplayed: ['midnight', 'sunset'],
			useUpdateInterval: true,
			updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
			animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
			language: config.language,
			showAdzanAlert: true,
			showTomorrow: true,
			alertTimer: 15000
		}
	}
```

**Comment by MrGitGo** [comment]
Oh now it worked, when I changed the language to 'en'. But I have tried this because the MyPayerTime was showing me the wrong times. And the times did not changed even when I changed the method. I have the same problem with this app

**Comment by slametps** [comment]
You should create your own module for using that API. But you may check the latest version because there are a new config entry methodSettings for custom prayer time calculation.
