### ISSUE TITLE
Fajr and Isha custom degrees based calculation 

### ISSUE THREAD

**Issue by webac** [slametps/MMM-PrayerTime#22]
Hi,

Is it possible to add 2 variables to customize Fajr and Isha time by specifying the degree calculation for each of these 2 prayers?
Here are the degrees I use:
Fajr: 15
Isha: 12

Everything works fine for me except the sound I changed the omxplayer command to
omxplayer -p -o local file.mp3
as I'm using an external jack speaker to play sound on my RPI

Thanks a lot
L

**Comment by slametps** [comment]
I did not do any calculation for the praying time. All the values are return from web API https://aladhan.com/prayer-times-api.

**Comment by webac** [comment]
Thanks,
Here is how I did for to customize Fajr and Isha angles:
I added this in config.js:
method: 99
methodSettings: '15,null,12',

and in MMM-PrayerTime.js this condition:
                if (this.config.methodSettings) {
                        params += "&methodSettings=" + this.config.methodSettings;
                }

https://aladhan.com/calculation-methods

**Comment by slametps** [comment]
Is it worked? If yes, you can do a PR.

**Comment by slametps** [comment]
don't forget to urlEncode the value of methodSettings.
