### ISSUE TITLE
Layout for horizontal

### ISSUE THREAD

**Issue by wsokc** [slametps/MMM-PrayerTime#27]
Hi

This as this much more about feature request.

How to show the adzan schedule in horizontal manner so we can put it into the center bottom ?
The current layout is meant for side positioning.
Is it possible to make like below instead :

**Next Pray Time : ISYA (Countdown timer)**

Time | fajr | dhuhr | asr | maghrib | Isya
------------ | ------------- | ------------ | ------------- |------------ | -------------
Today | Time | Time | Time | Time | Time |
Tomorrow | Time | Time | Time | Time | Time |

**Comment by slametps** [comment]
Unfortunately, it is not supported yet. But you can modify the modules and do a PR.

**Comment by slametps** [comment]
FYI, I'm working on horizontal view as requested except for countdown timer. Pls, stay tuned.

**Comment by wsokc** [comment]
> FYI, I'm working on horizontal view as requested except for countdown timer. Pls, stay tuned.

Thank you sir, looking forward to get the outcome.

**Comment by slametps** [comment]
I just finished adding the horizontal view. Please update your repo (git pull). Hope it is as you expected. :)

**Comment by wsokc** [comment]
Really awesome, many thanks!

**Comment by slametps** [comment]
ywc
