### ISSUE TITLE
How to stop playing adzan?

### ISSUE THREAD

**Issue by tanvir586** [slametps/MMM-PrayerTime#29]
{
         		module: 'MMM-PrayerTime',
                        header: "CARDIFF PRAYER TIME",
        		position: 'top_left',	// This can be any of the regions. Best result is in the top_left/top_right.
        		config: {
        			apiVersion: '1.0', // please, leave unchanged. reserved for future use.
        			lat: 51.5199,
        			lon: -3.204,
         			timezone: 'Europe/London',
        			timeFormat: 12,
        			method: 3,
        			playAdzan: false,
        			notDisplayed: ['imsak', 'midnight', 'sunset'],
        			useUpdateInterval: true,
        			updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
        			animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
        			language: 'en',
        			showAdzanAlert: false,
        			showTomorrow: true,
        			vertical: true, // set false for horizontal view
        			alertTimer: 15000
         		}
        	},

False value not working.

**Comment by slametps** [comment]
`playAdzan: []`
