### ISSUE TITLE
this model is not work 

### ISSUE THREAD

**Issue by nojoom4000** [slametps/MMM-PrayerTime#3]
hi my bro
I downloaded this module to my MM
and config all codes 
but not work 
did I have some issues when I config?or the module is not work?

**Comment by slametps** [comment]
Post your config.js.

**Comment by slametps** [comment]
Also your pm2 log and capture your screen/browser.

**Comment by slametps** [comment]
How is your progress?

**Comment by nojoom4000** [comment]
0|mm       | Loading config ...
0|mm       | Loading module helpers ...
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: updatenotification
0|mm       | No helper found for module: helloworld.
0|mm       | All module helpers loaded.
0|mm       | Starting server on port 8080 ...
0|mm       | Server started ...
0|mm       | Connecting socket for: updatenotification
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.
0|mm       |
0|mm       | > magicmirror@2.1.3 start /home/pi/MagicMirror
0|mm       | > sh run-start.sh
0|mm       |

0|mm       | Starting MagicMirror: v2.1.3
0|mm       | Loading config ...
0|mm       | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
0|mm       | Loading module helpers ...
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: updatenotification
0|mm       | No helper found for module: helloworld.
0|mm       | All module helpers loaded.
0|mm       | Starting server on port 8080 ...
0|mm       | Server started ...
0|mm       | Connecting socket for: updatenotification
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.
this is my log 


/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config =
{
        address: "0.0.0.0",
        electronOptions: {

        },
        ipWhitelist: [

        ],
        timeFormat: 12,
        modules: [
{
                module: 'MMM-PrayerTime',
                position: 'top_left',   // This can be any of the regions. Best result is in the top_left/top_right.
                config: {
                        apiVersion: '1.0' // please, leave unchanged. reserved for future use.
                        lat: false, // latitude of your position (city)
                        lon: false, // longitude of your position (city)
                        timezone: false, // please refer to http://php.net/manual/en/timezones.php
                        timeFormat: 24,
                        method: 5,
                        playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
                        notDisplayed: ['midnight', 'sunset'],
                        useUpdateInterval: true,
                        updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
                        animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
                        language: config.language,
                        showAdzanAlert: true,
                        alertTimer: 15000
                }
        }

],

this is my config

**Comment by nojoom4000** [comment]
I change some lines in config is work now 
done
thanks

**Comment by johymon** [comment]
apiVersion: '1.0'   coma missing at end &
add lat and lon

**Comment by johymon** [comment]
apiVersion: '1.0' coma missing at end &
add lat and lon

**Comment by slametps** [comment]
@nojoom4000 : glad to hear that. I'll close this issue.
