### ISSUE TITLE
module stuck in 'loading'

### ISSUE THREAD

**Issue by hrjmsh** [slametps/MMM-PrayerTime#30]
For the last few days, the module MMM-PrayerTime has been unable to load. I have tried npm install async but nothing seems to work.
On the screen, it just says ‘loading’?

**Comment by belfasti** [comment]
Azan stopping halfway, please help

**Comment by slametps** [comment]
> Azan stopping halfway, please help

Check the other thread.

**Comment by slametps** [comment]
> For the last few days, the module MMM-PrayerTime has been unable to load. I have tried npm install async but nothing seems to work.
> On the screen, it just says ‘loading’?

Have you got this module loaded succesfully before? Or, from the first install, it is already not loaded as expected?

**Comment by hrjmsh** [comment]
It has been on my Magic Mirror since 2018. Has been fine throughout all the Magic Mirror and Raspbian upgrades. Only recently, it has started to have this problem.

**Comment by masnizar** [comment]
any solution ho to solved keep loading issue and how to check detail log
![image](https://user-images.githubusercontent.com/62639473/77844861-aac4f600-71dc-11ea-8d65-fa956a5bb972.png)
Thanks

**Comment by hrjmsh** [comment]
> any solution ho to solved keep loading issue and how to check detail log
> ![image](https://user-images.githubusercontent.com/62639473/77844861-aac4f600-71dc-11ea-8d65-fa956a5bb972.png)
> Thanks

I left it like that and it started working a few days later.

**Comment by slametps** [comment]
you have to ensure that your internet connection is ready before starting the module. If you want to update more regularly, you need to change value of `updateInterval` with less value (86400 means the update is once a day).

**Comment by Zamy97** [comment]
I am having the same issue! It was working fine for the past few months but it randomly started showing loading only. 

I ran the npm start dev and on the browser it is showing MMM-PrayterTime: got HTTP status -0 and then it is showing some error from api.aladhan.com/timing as well. Any help please?

**Comment by Zamy97** [comment]
for those that might come here after me! the aladhan.com updated their api so lemme see if I can make a pr to fix it. i was able to fix it in my system.

**Comment by slametps** [comment]
> for those that might come here after me! the aladhan.com updated their api so lemme see if I can make a pr to fix it. i was able to fix it in my system.

Pls feel free to send a PR.

**Comment by hrjmsh** [comment]
It has been stuck for the last couple of weeks. Please let me know how you fixed it as this module was the sole reason for me to make the Magic Mirror and I adore the sound of Adhan being heard in my house.

**Comment by slametps** [comment]
pls update your local copy for latest update (fix).

**Comment by masnizar** [comment]
Now i can hear Adzan again after updated to the latest update. Thanks,

**Comment by hrjmsh** [comment]
Working now! Thank you.
