### ISSUE TITLE
Azan stopping halway through

### ISSUE THREAD

**Issue by belfasti** [slametps/MMM-PrayerTime#31]
Azan start playing but stopping halfway through.

Check Adzan.mp3 by playing on iTunes, it is fine but on mmm-prayer time it stops halfway 

Please help

**Comment by slametps** [comment]
still no idea why this happened because it is reported for the first time.
pls check playing using omxplayer as following:

`/usr/bin/omxplayer -o both modules/MMM-PrayerTime/res/Adzan.mp3.`
