### ISSUE TITLE
Azan not playing at all 

### ISSUE THREAD

**Issue by Cihangir7000** [slametps/MMM-PrayerTime#32]
I am using raspberry pi 4 and have latest MagicMirror, I have installed this module, it works but it’s not playing any azan at all. 
What to do ? 
Best regards

**Comment by slametps** [comment]
Do you have omxplayer installed?

**Comment by Cihangir7000** [comment]
Yes I have installed it.

**Comment by slametps** [comment]
can you hear adzan by executing following command in shell?

`
/usr/bin/omxplayer -o both modules/MMM-PrayerTime/res/adzan.mp3
`

**Comment by Cihangir7000** [comment]
Thank you so much for feedback, can you also tell me please , does omxplayer should be installed in a specific directory, I tried to run this in terminal but I got error File "modules/MMM-PrayerTime/res/adzan.mp3" not found.

**Comment by Cihangir7000** [comment]
Hello slametps, I have now tired this way :- /usr/bin/omxplayer -o both /home/pi/MagicMirror/modules/MMM-PrayerTime/res/adzan.mp3
And this gives med this result :- Audio codec mp3float channels 2 samplerate 16000 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
have a nice day ;)
No sound at all !
I want to telle you that I am using "RASPIAUDIO.COM Audio DAC HAT Sound Card (Audio+Speaker+MIC) for Raspberry Pi4 /Pi Zero / Pi3 / Pi3B / Pi3B+ / Pi2 / " [https://www.raspiaudio.com/raspiaudio-aiy](url)

**Comment by slametps** [comment]
Is you raspi able to play other sound/mp3? It is raspi issue. FYI, i have no experience with that sound card.

**Comment by Cihangir7000** [comment]
although issue remains but I agree that it's a raspi issue.
