### ISSUE TITLE
Adzan Alert Not Display at all 

### ISSUE THREAD

**Issue by masnizar** [slametps/MMM-PrayerTime#33]
Assalamu'alaikum Bang Slametps,

Thank you creating MMM_PlayerTime Module, I pray that Allah subhanahu wa ta’ala is keeping you and your loved ones in His Divine Blessings and Favours, Ameen.
I Installed your MMM_PlayerTime Module, but Adzan Notification not show on MagicMirror.
Kindly help to check if any wrong parameter I missed, 
here config module MMM-PrayerTime on my MagicMirror
    {
      module: 'MMM-PrayerTime',
      position: 'top_left',
      header: 'Prayer Time Petaling Jaya, MY',
      config: {
        lat: 3.127887,
        lon: 101.59449,
        timezone: 'Asia/Kuala_Lumpur',
        method: 11,
        playAdzan: [
          'fajr',
          'dhuhr',
          'asr',
          'maghrib',
          'isha'
        ],
        notDisplayed: [
          'midnight',
          'sunset'
        ],
        language: 'id',
	updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
	animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
        showAdzanAlert: true,
	showTomorrow: true,
        vertical: true, // set false for horizontal view
	alertTimer: 60000
      }
    },

Thank You
Masnizar

**Comment by slametps** [comment]
Wa"alaikumsalam.
is the prayer schedule displayed correctly?

**Comment by masnizar** [comment]
Yes, the player schedule displayed correctly 

![image](https://user-images.githubusercontent.com/62639473/77528159-6548b600-6ec8-11ea-90fc-bf9332f8c4fd.png)

**Comment by masnizar** [comment]
Sorry maybe i'm not notice Azdan alert. after change parameter value more bigger then i can see.
thank you mas.
![image](https://user-images.githubusercontent.com/62639473/77531639-333a5280-6ece-11ea-9af4-cf0782fa4677.png)
