### ISSUE TITLE
MMM-PrayerTime Module not starting

### ISSUE THREAD

**Issue by HESSEBO** [slametps/MMM-PrayerTime#34]
I installed the module and configuration file but when I restart MM it gives me an error. 

here's my config file : 

	{
			module: 'MMM-PrayerTime',
			position: 'top_left',
			config: {
				apiVersion: '1.0', 
				lat: 26.398881, 
				lon: 50.203521, 
				timezone: Asia/Riyadh, 
				timeFormat: 12,
				method: 5,
				playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
				notDisplayed: ['midnight', 'sunset'],
				useUpdateInterval: true,
				updateInterval: 86400 * 1000, 
				animationSpeed: 2.5 * 1000, 
				language: 'ar',
				showAdzanAlert: true,
				showTomorrow: true,
				vertical: false, 
				alertTimer: 15000
			}
		},

**Comment by HESSEBO** [comment]
It worked. I found the issue in timezone line. I just removed it and then restarted the MagicMirror.
Thanks anyway for your great work

**Comment by slametps** [comment]
You just simply change with the following line:

```
timezone: 'Asia/Riyadh',
```
