### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by hm1234** [slametps/MMM-PrayerTime#37]
I am trying to play audio through a usb audio controller or through a bluetooth speaker. This module runs on omxplayer that does not support either. I wanted to know if there is a way to change the module to use another player maybe VLC?

**Comment by slametps** [comment]
It might. You can try modify the call in node_helper.js. pls let me know if succeed.

**Comment by hm1234** [comment]
I got it working with VLC

**Comment by slametps** [comment]
Awesome.

**Comment by ilhanaksoy** [comment]
Hi @hm1234 & @slametps 
I can't install omxplayer either, but I have VLC. What do I have to change in the configs so that VLC plays the adhan? 

Thanks in advance
Ilhan
