### ISSUE TITLE
Hanafi

### ISSUE THREAD

**Issue by hm1234** [slametps/MMM-PrayerTime#38]
Any way to change to Hanafi schooling?

**Comment by slametps** [comment]
What is Hanafi schooling?

**Comment by hm1234** [comment]
Like this. 
![Screenshot_20200607-004025](https://user-images.githubusercontent.com/13208530/83960509-811cf080-a857-11ea-88d5-bf4bb71ddccc.jpg)

**Comment by slametps** [comment]
Currently, it is only support some calculated methods provided by Aladhan API described at https://aladhan.com/calculation-methods.

**Comment by hm1234** [comment]
![Screenshot_20200607-004512](https://user-images.githubusercontent.com/13208530/83960582-49627880-a858-11ea-9fad-fc5201cb3b9e.jpg)
I tried adding school: 1 to the config but the times didn't change

**Comment by slametps** [comment]
All the paramaters are passed to Aladhan API. The calculation is done by Aladhan not the MMM-PrayerTime. If you got the same prayer times, it assume that's the calculation result by Aladhan based on calculation-method. You may try other valid option's value.

**Comment by slametps** [comment]
Please update your repo. I added the missing `school` parameter.

**Comment by hm1234** [comment]
Just updated it and it's working thank you.
