### ISSUE TITLE
How do you shorten the Adzan?

### ISSUE THREAD

**Issue by sulaimanpie** [slametps/MMM-PrayerTime#39]
I recently a built a Magic Mirror but i would just like to know how to shorten the Adzan to around 30 seconds

**Comment by slametps** [comment]
What do you mean by shortening the Adzan? If you mean the adzan recitement, you just simply replace `adzan.mp3` and `adzan-fajr.mp3` on folder `res` with your own.

**Comment by sulaimanpie** [comment]
I added my own audio that was shorter and it worked. Thank you very much
