### ISSUE TITLE
Modules don´t work

### ISSUE THREAD

**Issue by 1Adel** [slametps/MMM-PrayerTime#4]
hey brother,
the module doesn´t work, the same with the MMM-RandomQuranAyah Module.
A great work from yourside Allah ibarik fik.

here my Config:
=============================================================
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 */

var config = {
	port: 8085,
	// address: ( The ip address the accept connections. The default open bind :: is IPv6 is available or 0.0.0.0 IPv4 run on. Example config: 192.168.10.100.)
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.253.1/120", "192.168.253.1/24"], // Set [] to allow all IP addresses.
	// zoom: 1.0 (This allows to scale the mirror contents with a given zoom factor. The default value is 1.0)
	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [
				{
				module: "MMM-RandomQuranAyah",
					position: "top_bar",	
					config: {
						apiVersion: "1.0", 
						showArabic: true,
						showTranslation: true,
						surahArabicName: true,
						translationLang: "de.bubenheim",
						updateInterval: 3600 * 1000, 
						animationSpeed: 2500,
							}
				},
				{
				 module: "MMM-PrayerTime",
					position: "top_right",
					config: {
						apiVersion: "1.0",
						lat: 50.764058,
						lon: 7.052036,
						timezone: "Europe/Berlin",
						method: 3,
						playAdzan: ["dhuhr", "asr", "maghrib", "isha"],
						notDisplayed: ["midnight", "sunset", "imsak"],
						useUpdateInterval: true,
						updateInterval: 86400 * 1000,
						animationSpeed: 2.5 * 1000,
						language: "en",
						showAdzanAlert: true,
						alertTimer: 15000
							}
				},
			]
			};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

=============================================================

**Comment by slametps** [comment]
Can you post your MM or pm2 log?

**Comment by 1Adel** [comment]
i had problem with async, followed command helped me:
npm install async --save

 many thanks, i will try lokk if the sound word athan worls or not.. 
My MM is installed as a Docker Container in a synology NAS and the client is a raspberry with a fullscreen mode as a kiosk mode

**Comment by slametps** [comment]
@1Adel : sound adzan is played locally via omxplayer. You should modify it first to play in your client browser.
