### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by uok825** [slametps/MMM-PrayerTime#40]
Config.js
`		{
			module: "MMM-PrayerTime",
			position: "bottom-right",	// This can be any of the regions. Best result is in the top_left/top_right.
			config: {
				apiVersion: "1.0", // please, leave unchanged. reserved for future use.
				lat: 37.871540, // latitude of your position (city)
				lon: 32.498914, // longitude of your position (city)
				timezone: Europe/Istanbul, // please refer to http://php.net/manual/en/timezones.php
				timeFormat: 24,
				method: 13,
				playAdzan: [],
				notDisplayed: ["midnight", "sunset"],
				useUpdateInterval: true,
				updateInterval: 4 * 60 * 1000, // How often do you want to fetch new praying time? (milliseconds)
				animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
				language: en,
				showAdzanAlert: false,
				showTomorrow: true,
				vertical: false, // set false for horizontal view
				alertTimer: 15000
			}`

**Comment by uok825** [comment]
I got Please create a config file error.

**Comment by uok825** [comment]
![image](https://user-images.githubusercontent.com/30076213/85853054-82886b80-b7ba-11ea-8b6b-4f05b8595d4b.png)
found the issue

**Comment by slametps** [comment]
Your config should be as following:

```
{ 
  module: "MMM-PrayerTime", 
  position: "bottom-right", 
  // This can be any of the regions. Best result is in the top_left/top_right. 
  config: { 
    apiVersion: "1.0", // please, leave unchanged. reserved for future use. 
    lat: 37.871540, // latitude of your position (city) 
    lon: 32.498914,  // longitude of your position (city) 
    timezone: 'Europe/Istanbul',  // please refer to http://php.net/manual/en/timezones.php 
    timeFormat: 24, 
    method: 13, 
    playAdzan: [], 
    notDisplayed: ["midnight", "sunset"], 
    useUpdateInterval: true, 
    updateInterval: 4 * 60 * 1000, 
    // How often do you want to fetch new praying time? (milliseconds) 
    animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds) 
    language: en, 
    showAdzanAlert: 
    false, 
    showTomorrow: 
    true, 
    vertical: false, // set false for horizontal view     
    alertTimer: 15000 
  }
}
```
