### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by hm1234** [slametps/MMM-PrayerTime#42]
I keep getting magic mirror config issue

		{ 
		  module: "MMM-PrayerTime", 
		  position: "top-right", 
		  config: { 
		    apiVersion: "1.0", // please, leave unchanged. reserved for future use. 
		    lat: 33.957245, // latitude of your position (city) 
		    lon: -83.988441,  // longitude of your position (city) 
		    timezone: 'America/New_York',  // please refer to http://php.net/manual/en/timezones.php 
		    timeFormat: 12, 
		    method: 5, 
		    playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'], 
		    notDisplayed: ['midnight', 'sunset'], 
		    useUpdateInterval: true, 
		    updateInterval: 4 * 60 * 1000, // How often do you want to fetch new praying time? (milliseconds) 
		    animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds) 
		    language: en, 
		    showAdzanAlert: true, 
		    showTomorrow: true, 
		    vertical: true, // set false for horizontal view     
		    alertTimer: 15000 
		  }
		},

that's my congif and magic mirror is newly installed and only module

**Comment by slametps** [comment]
{ 
	  module: "MMM-PrayerTime", 
	  position: "top-right", 
	  config: { 
	    apiVersion: "1.0", // please, leave unchanged. reserved for future use. 
	    lat: 33.957245, // latitude of your position (city) 
	    lon: -83.988441,  // longitude of your position (city) 
	    timezone: 'America/New_York',  // please refer to http://php.net/manual/en/timezones.php 
	    timeFormat: 12, 
	    method: 5, 
	    playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'], 
	    notDisplayed: ['midnight', 'sunset'], 
	    useUpdateInterval: true, 
	    updateInterval: 4 * 60 * 1000, // How often do you want to fetch new praying time? (milliseconds) 
	    animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds) 
	    language: 'en',  // this is the correct one. Pls compare with yours
	    showAdzanAlert: true, 
	    showTomorrow: true, 
	    vertical: true, // set false for horizontal view     
	    alertTimer: 15000 
	  }
	},

**Comment by hm1234** [comment]
oh I see I forgot the '' around en. Thanks solved the issue
