### ISSUE TITLE
ALSA support

### ISSUE THREAD

**Issue by 74Km** [slametps/MMM-PrayerTime#44]
Hello, I really like what you did with this module. I use the adzan announcement a lot but often 100% of the volume is way too loud. and I was not able to change the volume or mute. I learned that it plays the audio through omxplayer, so I researched it so I ended up doing the following to the node_helper.js file: 

Replace "/usr/bin/omxplayer -o both" with "/usr/bin/omxplayer -o alsa"

I am very new to programming so I might be wrong, but it worked for me!

Thanks

**Comment by slametps** [comment]
I control the volume via sound volume of raspberry or (TV) monitor I used.

**Comment by 74Km** [comment]
Oh, I see, if you connect to a TV then the volume is not a problem. I'll close this then, hopefully, if anyone wants to use the desktop volume control this post will help!
