### ISSUE TITLE
Can't remove FIRSTTHIRD and LASTTHIRD

### ISSUE THREAD

**Issue by M-Moghazi** [slametps/MMM-PrayerTime#48]
I can't customized to remove the FIRSTTHIRD and LASTTHIRD from prayers, I tried to add it to 'notDisplayed' but it doesn't work. and I can't find it also in MMM-PrayerTime.js

I'm kinda new to this also, but this is really important for me to fix

<img width="672" alt="Screenshot 2023-02-15 at 9 53 02 PM" src="https://user-images.githubusercontent.com/11007954/219125042-1f508476-21e8-44a7-b58d-3f406348bcfa.png">

**Comment by slametps** [comment]
apparently, FIRSTTHIRD and LASTTHURTD are additional labels. I need to modify the code first to make them optional to display or not.

**Comment by slametps** [comment]
you should simply add `firstthird` and `lastthird` into option `notDisplayed` in your config, and make sure to enter them in lowercase, as following:
`
notDisplayed: ['midnight', 'sunset', 'firstthird', 'lastthird']
`

**Comment by M-Moghazi** [comment]
it worked for me, was adding it to notDisplay in uppercase
