### ISSUE TITLE
Prayer time display issue

### ISSUE THREAD

**Issue by sayingithub** [slametps/MMM-PrayerTime#49]
Hi, 
First, I would like to thank the creator of this moduleI and manage to configure it in Magic Mirror.
But, I am getting 2 additional timings get listed "LASTTHIRD" and "FIRSTTHIRD" and don't want to display it. Any advice? thanks

**Comment by slametps** [comment]
please check this [issue](https://github.com/slametps/MMM-PrayerTime/issues/48).

**Comment by sayingithub** [comment]
Thanks a lot for your quick response and it is working fine now.
I am using "vertical: false" due to screen size limitation. I have more space horizontally and would like to provide more spaces between the prayers time. Do we have option to do it in config or in the css? thanks in advance.
