### ISSUE TITLE
Playing Adhan out loud

### ISSUE THREAD

**Issue by moinahmed001** [slametps/MMM-PrayerTime#5]
I am having difficulty getting it to play out loud on the Android tablet. 
The app is hosted on pi. I have uncommented
` self.todaySchedule = ...` and placed the time close as possible to current time. I see the pop up, however no sound appearing.

Am I missing anything?

**Comment by slametps** [comment]
Sorry, this module plays adzan at server-side through omxplayer. So, the sound will be available in server only, not in the client e.g. at your tablet browser. You should modify this module to play in client-side.
