### ISSUE TITLE
DE-localization does not load

### ISSUE THREAD

**Issue by ilhanaksoy** [slametps/MMM-PrayerTime#50]
Hi,

I have successfully installed the module, it is loaded and displayed by MM without errors.

However, I have the problem that the de-localization does not load as expected.

I can find de.json in the "translations" folder, the texts also fit, but the config-lang en is always displayed.

Could someone tell me where I could have configured it incorrectly?

Thank you very much,
Ilhan

**Comment by ilhanaksoy** [comment]
The problem was the language settings of Magic-Mirror itself. I thought I could use a different language than the one used by MM.

**Comment by slametps** [comment]
Of course, you could use different language for this module.
Set config `language = "de";` in MMM-PrayerTime config file.

**Comment by ilhanaksoy** [comment]
This my Config for MM:

config = {
	address: "localhost",	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/",			// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
					  		// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-EN",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",


and here the config for MMM-PrayerTime-Module:

{
			module: 'MMM-PrayerTime',
			position: 'top_center', 			// This can be any of the regions. Best result is in the top_left/top_right.
			config: {
				apiVersion: "1.0", 				// please, leave unchanged. reserved for future use.
				lat: 51.4344079, 				// latitude of your position (city)
				lon: 6.7623293, 				// longitude of your position (city)
				timezone: 'Europe/Berlin', 		// please refer to http://php.net/manual/en/timezones.php
				timeFormat: 24,
				method: 13,						// Diyanet
				playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
				notDisplayed: ['midnight', 'sunset', 'firstthird', 'lastthird'],
				useUpdateInterval: true,
				updateInterval: 86400 * 1000, 	// How often do you want to fetch new praying time? (milliseconds)
				animationSpeed: 2.5 * 1000, 	// Speed of the update animation. (milliseconds)
				language: "de",
				showAdzanAlert: true,
				showTomorrow: true,
				vertical: true, 				// set false for horizontal view
				alertTimer: 15000
		}
		},


Do you have any idea what I have done wrong?
