### ISSUE TITLE
Module does not work, what's wrong with my setting?

### ISSUE THREAD

**Issue by omarjanudin** [slametps/MMM-PrayerTime#6]
shows only **Loading...**			

module: 'MMM-PrayerTime',
			position: 'middle_center',	// This can be any of the regions. Best result is in the top_left/top_right.
			config: {
			apiVersion: '1.0', // please, leave unchanged. reserved for future use.
			2.9423332: true, // latitude of your position (city)
			101.7204208: true, // longitude of your position (city)
			kuala_lumpur: true, // please refer to http://php.net/manual/en/timezones.php
			timeFormat: 24,
			method: 5,
			playAdzan: ['subuh', 'zohor', 'asar', 'maghrib', 'isyak'],
			notDisplayed: ['midnight', 'sunset'],
			useUpdateInterval: true,
			updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
			animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
			language: 'en',
			showAdzanAlert: true,
			alertTimer: 15000

**Comment by slametps** [comment]
Your config is completely incorrect.
Your config should be as following:

{
			module: 'MMM-PrayerTime',
			header: 'Jadwal Sholat',
			position: 'top_left',
			config: {
				lat: 2.9423332,
        lon: 101.7204208,
        timezone: 'Asia/Kuala_Lumpur',
        timeFormat: 24,
        method: 5,
        playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
        useUpdateInterval: true,
        updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
        animationSpeed: 2.5 * 1000, // Speed of the update animation. (Milliseconds)
        alertTimer: 30000,
        language: 'en',
			}
		},

**Comment by slametps** [comment]
Your config is almost completely incorrect.
Your config should be as following:

`
		{
			module: 'MMM-PrayerTime',
			header: 'Jadwal Sholat',
			position: 'top_left',
			config: {
				lat: 2.9423332,
        lon: 101.7204208,
        timezone: 'Asia/Kuala_Lumpur',
        timeFormat: 24,
        method: 5,
        playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
        useUpdateInterval: true,
        updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
        animationSpeed: 2.5 * 1000, // Speed of the update animation. (Milliseconds)
        alertTimer: 30000,
        language: 'en',
			}
		},
`
