### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Raimouny** [slametps/MMM-PrayerTime#8]
I am new to this every time i copy the module to config.js I get an error can anybody help

**Comment by slametps** [comment]
Can you post your config?

**Comment by Raimouny** [comment]
modules: [
	{
		module: 'MMM-PrayerTime',
		position: 'Bottom_left',	.
		config: {
			apiVersion: '1.0',
			lat: false, 31.972836
			lon: false,35.898916
			timezone: false, // please refer to http://php.net/manual/en/timezones.asia.php
			timeFormat: 12,
			method: 5,
			playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
			notDisplayed: ['midnight', 'sunset'],
			useUpdateInterval: true,
			updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
			animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
			language: config.language,
			showAdzanAlert: true,
			alertTimer: 15000
		}
	}
]

**Comment by slametps** [comment]
Your config should be as following:

modules: [
{
module: 'MMM-PrayerTime',
position: 'bottom_left',	.
config: {
apiVersion: '1.0',
lat: 31.972836,
lon: 35.898916,
timezone: 'Asia/Dubai', // please refer to http://php.net/manual/en/timezones.asia.php
timeFormat: 12,
method: 5,
playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
notDisplayed: ['midnight', 'sunset'],
useUpdateInterval: true,
updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
language: config.language | 'en',
showAdzanAlert: true,
alertTimer: 15000
}
}
]

**Comment by Raimouny** [comment]
Thank you very much but two issues please:
1. I live in Amman Jordan so should I change The Name " Asia/Dubai" to Asia/Amman"
2. Again i am new to this , so should I just copy and paste in the config.js file

**Comment by slametps** [comment]
1. Asia/Amman it is.
2. You should try it first.

**Comment by Raimouny** [comment]
I really appreciate your help, but still i am receiving error can you send me your email I can email you my config.js file for you to look at.

**Comment by Raimouny** [comment]
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "metric",

	modules: modules: [
{
                            module: 'MMM-PrayerTime',
                            position: 'bottom_left',	.
                            config: {
                            apiVersion: '1.0',
                            lat: 31.972836,
                            lon: 35.898916,
                            timezone: 'Asia/Amman', // please refer to http://php.net/manual/en/timezones.asia.php
                            timeFormat: 12,
                            method: 5,
                            playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
                            notDisplayed: ['midnight', 'sunset'],
                            useUpdateInterval: true,
                            updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
                            animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
                            language: config.language | 'en',
                            showAdzanAlert: true,
                            alertTimer: 15000
}
}
]
[
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Jordan Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/52/Islam_Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Amman",
				locationID: "250441",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "ab57d83f3422600a3b4ef5ee3576c0e2"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Amman",
				locationID: "250441",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "ab57d83f3422600a3b4ef5ee3576c0e2"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "BBC Middle East",
						url: "http://feeds.bbci.co.uk/news/world/middle_east/rss.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by slametps** [comment]
Slametps@gmail.com.

**Comment by slametps** [comment]
/* Magic Mirror Config Sample
*

By Michael Teeuw http://michaelteeuw.nl
MIT Licensed.
For more information how you can configurate this file
See https://github.com/MichMich/MagicMirror#configuration
*/

var config = {
address: "localhost", // Address to listen on, can be:
// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
// - another specific IPv4/6 to listen on a specific interface
// - "", "0.0.0.0", "::" to listen on any interface
// Default, when address config is left out, is "localhost"
port: 8080,
ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
// or add a specific IPv4 of 192.168.1.5 :
// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

language: "en",
timeFormat: 12,
units: "metric",

modules: [
{
module: 'MMM-PrayerTime',
position: 'bottom_left',	.
config: {
apiVersion: '1.0',
lat: 31.972836,
lon: 35.898916,
timezone: 'Asia/Amman', // please refer to http://php.net/manual/en/timezones.asia.php
timeFormat: 12,
method: 5,
playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
notDisplayed: ['midnight', 'sunset'],
useUpdateInterval: true,
updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)
language: config.language | 'en',
showAdzanAlert: true,
alertTimer: 15000
}
},
{
module: "alert",
},
{
module: "updatenotification",
position: "top_bar"
},
{
module: "clock",
position: "top_left"
},
{
module: "calendar",
header: "Jordan Holidays",
position: "top_left",
config: {
calendars: [
{
symbol: "calendar-check-o ",
url: "webcal://www.calendarlabs.com/ical-calendar/ics/52/Islam_Holidays.ics"
}
]
}
},
{
module: "compliments",
position: "lower_third"
},
{
module: "currentweather",
position: "top_right",
config: {
location: "Amman",
locationID: "250441", //ID from http://www.openweathermap.org/help/city_list.txt
appid: "ab57d83f3422600a3b4ef5ee3576c0e2"
}
},
{
module: "weatherforecast",
position: "top_right",
header: "Weather Forecast",
config: {
location: "Amman",
locationID: "250441", //ID from http://www.openweathermap.org/help/city_list.txt
appid: "ab57d83f3422600a3b4ef5ee3576c0e2"
}
},
{
module: "newsfeed",
position: "bottom_bar",
config: {
feeds: [
{
title: "BBC Middle East",
url: "http://feeds.bbci.co.uk/news/world/middle_east/rss.xml"
}
],
showSourceTitle: true,
showPublishDate: true
}
},
]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by govabm** [comment]
salam Aleykum can somebody Help me iam new too,

maybe can you sent me your Config.js Data via email

**Comment by govabm** [comment]
this is my config file  

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [
                {
			module: 'MMM-PrayerTime',
			position: 'bottom_right',	.
			config: {
			apiVersion: '1.0',
			lat: 31.972836,
			lon: 35.898916,
			timezone: 'Asia/Dubai', // please refer to http://php.net/manual/en/timezones.asia.php
			timeFormat: 12,
			method: 5,
			playAdzan: ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha'],
			notDisplayed: ['midnight', 'sunset'],
			useUpdateInterval: true,
			updateInterval: 86400 * 1000, // How often do you want to fetch new praying time? (milliseconds)
			animationSpeed: 2.5 * 1000, // Speed of the update animation. (milliseconds)	
			language: config.language | 'en',
			showAdzanAlert: true,
			alertTimer: 15000
			}
		},

		{
			module: "alert",
		},

		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Ferien NRW",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

for beginn to run the SM i get this message

tarting MagicMirror: v2.4.1
Loading config ...
WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: helloworld.
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Sockets connected & modules started ...
Launching application.
Shutting down server...
Stopping module helper: updatenotification

and then the SM run but with the text to config the file 

Barakallahufeek for Helping

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @Raimouny)
